apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ceres
  name: ceres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ceres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ceres
    spec:
      containers:
      - image: ceres-in-docker:0.5
        imagePullPolicy: Never
        name: ceres-in-docker
        env:
        - name: MANAGEMENT_SERVER_PORT
          value: "8081"
        ports:
        - containerPort: 8080
        resources: {}
status: {}