version: "3.8"

services:
  cassandra:
    image: cassandra:3.11
    ports:
    - 9042:9042
    volumes:
    - cassandra:/var/lib/cassandra
  redis:
    image: redis:6.0
    ports:
    - 6379:6379
    volumes:
    - redis:/data

volumes:
  cassandra: {}
  redis: {}
