ceres:
  downsample:
    granularities:
      - width: 5s
        ttl: 30m
        partitionWidth: 30s
      - width: 10s
        ttl: 30m
        partitionWidth: 30s
      - width: 30s
        ttl: 30m
        partitionWidth: 30s
      - width: 1m
        ttl: 1h
        partitionWidth: 2m
      - width: 2m
        ttl: 1h
        partitionWidth: 2m
      - width: 10m
        ttl: 1h
        partitionWidth: 10m
    last-touch-delay: 5s
    partitions: 4
    initial-processing-delay: 5s
    processing-threads: 5
    downsample-process-period: 5s
    downsample-spread-period: 10s
    set-hashes-process-limit: 2
    max-downsampling-time: 10m
    old-timeslot-clean-interval: 20m
  tag-filter: truncate
  tag-value-limit: 50
  excluded-tag-keys: ["ip_address"]
  ingest-start-time: 7d
  ingest-end-time: 1d
spring:
  data:
    cassandra:
      local-datacenter: datacenter1
management:
  server:
    port: 8081