spring:
  data:
    cassandra:
      keyspace-name: tsdb
      local-datacenter: datacenter1
      schema-action: create_if_not_exists
server:
  error:
    include-message: always
  compression:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, metrics, prometheus, threaddump
  metrics:
    export:
      influx:
        db: actuator-tsdb-cassandra
        enabled: false
  endpoint:
    health:
      show-components: always