ceres:
  downsample:
    granularities:
      - width: 30s
        ttl: 12h
        partitionWidth: 2h
      - width: 1m
        ttl: 1d
        partitionWidth: 4h
    time-slot-width: 1m # must be multiple of max granularity width
    last-touch-delay: 5s
    downsample-process-period: 32s
    partitions: 4
    partitions-to-process: 0-3
    processing-threads: 10
  tag-filter: truncate
  tag-value-limit: 50
  excluded-tag-keys: ["ip_address"]
  ingest-start-time: 7d
  ingest-end-time: 1d
spring:
  data:
    cassandra:
      local-datacenter: datacenter1
management:
  server:
    port: 8081