ceres:
  downsample:
    granularities:
      - width: 30s
        ttl: 30m
        partitionWidth: 30s
      - width: 1m
        ttl: 1h
        partitionWidth: 1m
    last-touch-delay: 5s
    partitions: 4
    initial-processing-delay: 5s
    processing-threads: 5
  tag-filter: truncate
  tag-value-limit: 50
  excluded-tag-keys: ["ip_address"]
  ingest-start-time: 7d
  ingest-end-time: 1d
spring:
  data:
    cassandra:
      local-datacenter: datacenter1
management:
  server:
    port: 8081