jobs:
  granularities:
    - partitionWidth: 15m
    - partitionWidth: 30m
    - partitionWidth: 1h
    - partitionWidth: 6h
    - partitionWidth: 12h
  partitions: 128
  max-downsample-job-duration: 30s
  cluster-ip: 10.80.6.120
server:
  port: 8080
logging:
  level:
    root: INFO
