buffer:
  max_num: 6000
spring:
  data:
    mongodb:
      uri: mongodb://mongo-mongodb/ceres?minPoolSize=100&maxPoolSize=500&maxIdleTimeMS=900000
server:
  port: 8085
logging:
  level:
    root: INFO
