apiVersion: v1
kind: ConfigMap
metadata:
  name: ceres
data:
  application.yml: |-
    ceres:
      downsample:
        granularities:
          - width: 5m
            ttl: 14d
            partitionWidth: 30m
          - width: 1h
            ttl: 365d
            partitionWidth: 1h
        partitions: 128
        last-touch-delay: 5s
        processing-threads: 5
      raw-ttl: 2d
      series-set-cache-size: 2000000
      tenant-tag: tenant
    logging:
      level:
        com.rackspace.ceres.app: debug
