apiVersion: v1
kind: ConfigMap
metadata:
  name: ceres
data:
  application.yml: |-
    jobs:
      granularities:
        - partitionWidth: 1m
        - partitionWidth: 5m
      partitions: 4
      max-downsample-job-duration: 10s
    logging:
      level:
        com.rackspace.ceres.app: info
