apiVersion: v1
kind: ConfigMap
metadata:
  name: rollupjobs
data:
  application.yml: |-
    jobs:
      granularities:
        - partitionWidth: 15m
        - partitionWidth: 30m
        - partitionWidth: 1h
        - partitionWidth: 6h
        - partitionWidth: 12h
      partitions: 128
      max-downsample-job-duration: 30s
    server:
      port: 8080
    logging:
      level:
        root: INFO
