name: Dev-Environment

on: 
  pull_request:
    types: [ closed ]
    branches: 
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_DEV }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gsutil cp gs://salus-mavenrepository/m2-settings.xml ./.mvn/settings.xml'

    - name: .m2 forder [*** fix it please ***]
      run: sed -i 's*/root/.m2/*./.m2/*g' ./.mvn/settings.xml

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '14'
        distribution: 'adopt-hotspot'

    - name: Build with Maven
      run: mvn -B verify -s .mvn/settings.xml

    - name: Image build
      run: docker build -t gcr.io/ceres-dev-222017/testdevops:latest .

    - name: Docker login
      run: gcloud auth configure-docker gcr.io -q

    - name: Image push
      run: docker push gcr.io/ceres-dev-222017/testdevops:latest