---
name: GCPSetup
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

    secrets:
      account:
        required: true
      GCPCreds:
        required: true

jobs:
  Setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCPCreds }}'

      - name: K8s login
        shell: bash
        run: |
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials primary-cluster --zone us-east1-b --project ${{ secrets.account }}
