---
name: Get Last version

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

    secrets:
      account:
        required: true
      GCPCreds:
        required: true
    outputs:
      version:
        description: "Last image version"
        value: ${{ jobs.version.outputs.version }}

jobs:
  Setup:
    uses: ./.github/workflows/getLastVersion.yml
    with:
      image: ${{ inputs.image }}
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_DEV }} 
  
  testit:
    runs-on:  ubuntu-latest
    needs: Setup

    steps:
      - run: echo ${{ needs.Setup.outputs.version }}
