---
name: PR Check

on: 
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - 'test-script'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - uses: ./.github/actions/GCPSetup
      #   with:
      #     GCPCreds: ${{ secrets.GCP_DEV }} 

      - uses: 'google-github-actions/setup-gcloud@v0'

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_DEV }}'

      - name: 'Maven settings'
        run: 'gsutil cp gs://salus-mavenrepository/m2-settings.xml ./.mvn/settings.xml'

      - name: .m2 forder [*** fix it please ***]
        run: sed -i 's*/root/.m2/*./.m2/*g' ./.mvn/settings.xml

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt-hotspot'

      - name: Build with Maven
        run: mvn -B verify -s .mvn/settings.xml

      - name: Image build
        run: docker build -t dummy-container .