name: PR check

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'test'
      run: 'git branch'

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_DEV }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gsutil cp gs://salus-mavenrepository/m2-settings.xml ./.mvn/settings.xml'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '14'
        distribution: 'adopt-hotspot'

    - name: alternatives
      run: sudo alternatives --list && sudo alternatives --set java /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/bin/java

    - run: echo $JAVA_HOME
    - run: sudo java --version

    - name: Build with Maven
      run: sudo mvn -B verify -s .mvn/settings.xml
