name: PR check

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_DEV }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gsutil cp gs://salus-mavenrepository/m2-settings.xml ./.mvn/settings.xml'

    - name: Install Java
      run: sudo sudo apt-get update && sudo apt-get install openjdk-14-jdk

    - run: echo $JAVA_HOME
    - run: java --version

    - name: Build with Maven
      run: sudo mvn -B verify -s .mvn/settings.xml
