---
name: Stage promotion

env:
  IMAGE_NAME: ceres
  HELM_CHART: ceres
  HELM_CHART_FOLDER: helm-ceres/cherts/ceres
  CLUSTER_NAME: primay-cluster

# Only trigger, when the build workflow succeeded
on:
#  workflow_run:
#    workflows: ["Dev-Smoke-test"]
#    types:
#      - completed
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/getVersion.yml
    with:
      image: testdevops
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_SA_JSON }} 

  promotion:
    runs-on: ubuntu-latest
    needs: Setup

    steps:

      ### Seting up runner env ###
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 

      - name: 'Maven settings'
        run: 'gsutil cp gs://salus-mavenrepository/m2-settings.xml ./.mvn/settings.xml'

      - name: .m2 forder [*** fix it please ***]
        run: sed -i 's*/root/.m2/*./.m2/*g' ./.mvn/settings.xml

      #Promoting image & artifact
      - name: 'Image promotion'
        run: gcloud container images add-tag gcr.io/${{ secrets.GCP_DEV_ACC }}/testdevops:latest gcr.io/${{ secrets.GCP_DEV_ACC }}/testdevops:${{ needs.Setup.outputs.new_version }}

      - name: 'POM promotion'
        shell: bash
        run: |
          mvn versions:set -DnewVersion=${{ needs.Setup.outputs.new_version }}
          git config --global user.email "mmi-automation@rackspace.com"
          git config --global user.name "mmi-automation"
          git add ./pom.xml
          git commit -m "${{github.workflow }}: ${{ github.run_number }} - POM.xml update new version: ${{ needs.Setup.outputs.new_version }}" || true
          git push origin master || true

      ### -Dversion=${{ needs.Setup.outputs.new_version }}-SNAPSHOT \
      - name: 'Artifact promotion'
        shell: bash
        run: |
          mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -DremoteRepositories=https://salus-artifactory.dev.monplat.rackspace.net/artifactory/libs-snapshot-local/ \
                            -DgroupId=com.rackspace.ceres \
                            -DartifactId=ceres \
                            -Dversion=0.0.1-SNAPSHOT \
                            -Dtransitive=false \
                            -Ddest=./ceres-${{ needs.Setup.outputs.new_version }}.jar
          
          # mvn deploy:deploy-file -Dfile=${{ needs.Setup.outputs.new_version }}.jar -DrepositoryId=salus-dev-releaselibs-release -DartifactId=ceres -DartifactId=com.rackspace.ceres
        
      - name: test
        run: |
          ls
          md5sum ceres-${{ needs.Setup.outputs.new_version }}.jar

  Stage-Deploy:
    runs-on: ubuntu-latest
    needs: [promotion]

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          GCPaccount: ${{ secrets.GCP_STAGE_ACC }}
          clusterName: $CLUSTER_NAME

      - name: Checkout helm-repo
        uses: actions/checkout@v3
        with:
          repository: rax-maas/helm-ceres
          ref: pre-prod
          path: helm-ceres
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: test k8s
        run: kubectl get pods

      - name: test helm
        run: helm show values helm-ceres/charts/ceres

#      - name: Helm upgrade
#        run: helm upgrade $HELM_CHART $HELM_CHART_FOLDER --set image.tag=${{ needs.Setup.outputs.new_version }}      
