---
name: Stage-promotion

env:
  IMAGE_NAME: ceres

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Dev-Smoke-test"]
    types:
      - completed
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/getVersion.yml
    with:
      image: testdevops
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_DEV }} 

  Image-promotion:
    runs-on: ubuntu-latest
    needs: Setup

    steps:

      ### Seting up runner env ###
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_DEV }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Set up Jfrog CLI'
        uses: jfrog/setup-jfrog-cli@v2

      - name: Checkout helm-repo
        uses: actions/checkout@v3
        with:
          repository: rax-maas/helm-ceres
          ref: master
          path: helm-ceres
          token: ${{ secrets.GIT_TOKEN }}

      #Promoting image & artifact
      - name: Retag
        run: gcloud container images add-tag gcr.io/${{ secrets.GCP_DEV_ACC }}/testdevops:latest gcr.io/${{ secrets.GCP_DEV_ACC }}/testdevops:${{ needs.Setup.outputs.new_version }}

      - name: Updating POM
        run: mvn versions:update-properties -Dproperties=${{ needs.Setup.outputs.new_version }}-SNAPSHOT -DincludeProperties={version} 

      - name: test POM
        run: cat POM.xml

      - name: promoting artifact
        run: echo "build me please"

      - name: test helm
        run: helm show values helm-ceres/charts/ceres

#      - name: Helm upgrade
#        run: helm upgrade helm-ceres $HELM_CHART --set image.repository=${IMAGE_NAME}@sha256,image.tag=${{ needs.Setup.outputs.new_version }}      
      
        
