---
name: testing

on:
  workflow_dispatch:
jobs:
  Setup:
    uses: ./.github/workflows/getLastVersion.yml
    with:
      image: testdevops
      account:  ${{ secrets.GCP_DEV_ACC }}
  testit:
    runs-on:  ubuntu-latest
    needs: Setup
    
    steps:
      - run: echo ${{ needs.Setup.outputs.version }}
