---
name: Tests automation Dev

on:
  workflow_run:
    workflows: ["Dev promotion"]
    types:
      - completed
  workflow_dispatch:

env:
    CLUSTER_NAME: primary-cluster
    SELECTOR: ceres-new
    LABEL: app.kubernetes.io/name
jobs:
  K8s:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          clusterName: $CLUSTER_NAME
          GCPaccount: ${{ secrets.GCP_DEV_ACC }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Pod Test
        run: python test-scripts/k8sPodStatus.py -l $SELECTOR -s $LABEL

  Readiness:
    runs-on: ubuntu-latest
    needs: ["K8s"]

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          clusterName: $CLUSTER_NAME
          GCPaccount: ${{ secrets.GCP_DEV_ACC }}

      - uses: ./.github/actions/k8sHelper
        with:
          action: port-forward
          service: ceres-new
          port-in: 7777
          port-out: 9000

      - run: python3 ./test-scripts/runTest.py -t Readiness -l ./test-scripts/test-plan.yml -d ./test-scripts

  Smoke-test:
    runs-on: ubuntu-latest
    needs: ["Readiness"]

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          clusterName: $CLUSTER_NAME
          GCPaccount: ${{ secrets.GCP_DEV_ACC }}

      - run: python3 ./test-scripts/runTest.py -t Smoke-test -l ./test-scripts/test-plan.yml -d ./test-scripts

  Functional-test:
    runs-on: ubuntu-latest
    needs: ["Readiness"]

    steps:
      - uses: actions/checkout@v3      
