---
name: testing if

on:
  workflow_call:
    inputs:
      testout:
        required: false
        type: boolean
        default: false
      
    outputs:
      version:
        description: "Last image version"
        value: ${{ jobs.test1.outputs.version }}
      
jobs:
  test1:
    name: test 1
    runs-on: ubuntu-latest

    outputs:
      #steps<id>.uptpus<out putname>
      version: ${{ steps.version.outputs.gcloud_version }}
  
    steps:

      - if: ${{ !inputs.testout }}
        shell: bash
        run: | 
          echo "VERSION=output1" >> $GITHUB_ENV
      
      - if: ${{ inputs.testout }}
        shell: bash
        run: | 
          echo "COMPOSE=compose" >> $GITHUB_ENV

      - run: echo "VERSION=ouput2-${{ env.COMPOSE }}" >> $GITHUB_ENV

      - run: echo ${{ env.VERSION}}

      - id: version
        shell: bash
        run: | 
          echo "::set-output name=gcloud_version::${{ env.VERSION}}"
