---
name: testing

on:
  workflow_dispatch:

env:
  account: ${{ secrets.GCP_DEV_ACC }}
  creds: ${{ secrets.GCP_DEV }}

jobs:
  # Setup:
  #   uses: ./.github/workflows/getLastVersion.yml
  #   with:
  #     image: testdevops
  #     account:  ${{ env.account }}
  #     GCPCreds: ${{ env.creds }}

  testit:
    runs-on:  ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/getLastVersion.yaml@master
        id: version
        with:
          image: testdevops
          account:  ${{ env.account }}
          GCPCreds: ${{ env.creds }}
      - run: echo ${{ steps.version.outputs.version }}
