---
name: testing2

on:
  workflow_dispatch:

env:
  packageManager: maven

jobs:
  seeit:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout helm-repo
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GIT_SSH }}

      - run: echo setup-java-${{ runner.os }}-${{ env.packageManager }}-${{ hashFiles('**/pom.xml') }}