---
name: testing

on:
  workflow_dispatch:

env:
  testy: ${{ secrets.GCP_STAGE_ACC }}
  testy2: "yolo"
  user-test: ${{ secrets.USER_TEST }}
  password-test: ${{ secrets.PASSWORD_TEST }}

jobs:
  testit:
    name: joby
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - run: |
          python -m pip install --upgrade pip
          pip install requests

      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import subprocess 
            import requests

            d = os.environ.copy
            f = dict(os.environ)

            print(d)
            print(f)

            user=f["user-test"] 
            password=f["password-test"]

            r = requests.get("http://salus-artifactory.dev.monplat.rackspace.net/artifactory/api/security/lockedUsers", auth=(user, password)) 
            print(r.status_code)
            print(r.json())
      
      - run: curl -u ${{ secrets.USER_TEST }}:${{ secrets.PASSWORD_TEST }} -X GET http://salus-artifactory.dev.monplat.rackspace.net/artifactory/api/security/lockedUsers

      - run: curl -u ${{ env.user-test }}:${{ env.password-test }} -X GET http://salus-artifactory.dev.monplat.rackspace.net/artifactory/api/security/lockedUsers