---
name: testing

on:
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/testingif.yml
      
  testit:
    runs-on:  ubuntu-latest
    needs: Setup

    steps:
      - run: echo ${{ needs.Setup.outputs.version }}
