---
name: testing if

on:
  workflow_call:
    inputs:
      testout:
        required: false
        type: boolean
        default: false
      
    outputs:
      version:
        description: "Last image version"
        value: ${{ jobs.version.outputs.version }}
      
jobs:
  test1:
    name: test 1
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.gcloud_version }}
  
    steps:
      - if: ${{ !inputs.testout }}
        id: version
        shell: bash
        run: | 
          echo "::set-output name=gcloud_version::output1"
      
      - if: ${{ inputs.testout }}
        id: version
        shell: bash
        run: | 
          echo "::set-output name=gcloud_version::output2"

      - run: echo run3