---
name: testing

on:
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/getVersion.yml
    with:
      image: testdevops
      
  testit:
    runs-on:  ubuntu-latest
    needs: Setup

    steps:
      - run: echo ${{ needs.Setup.outputs.currentVersion }}
      - run: echo ${{ needs.Setup.outputs.newVersion }}
