---
name: testing2

on:
  workflow_dispatch:

jobs:
  seeit:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout helm-repo
        uses: actions/checkout@v3
        with:
          repository: rax-maas/helm-ceres
          ref: master
          path: helm-ceres
          token: ${{ secrets.GIT_SSH }}
          
      - run: ls -la