---
name: testing2

on:
  workflow_dispatch:

jobs:
  seeit:
    runs-on:  ubuntu-latest

    steps:
      - uses: ./.github/actions/GCPSetup
        with:
          GCPaccount: ${{ secrets.GCP_DEV_ACC }}
          GCPCreds: ${{ secrets.GCP_DEV }} 
          k8sSetup: "TRUE"