---
name: testing

on:
  workflow_dispatch:

env:
  image: testdevops
  account: ${{ secrets.GCP_DEV_ACC }}
  GCPCreds: ${{ secrets.GCP_DEV }}

jobs:
  Setup:
    uses: ./.github/workflows/getLastVersion.yml
    with:
      image: testdevops
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_DEV_ACC }} 
      

  testit:
    runs-on:  ubuntu-latest
    
    steps:
      - run: echo ${{ steps.Setup.outputs.version }}
