---
name: testing

on:
  workflow_dispatch:

env:
  account: ${{ secrets.GCP_DEV_ACC }}
  creds: ${{ secrets.GCP_DEV }}

jobs:
  Setup:
    uses: ./.github/workflows/getLastVersion.yml
    with:
      image: testdevops
      account:  ${{ env.account }}
      GCPCreds: ${{ env.creds }}

  testit:
    runs-on:  ubuntu-latest
    needs: Setup
    
    steps:
      - run: echo ${{ needs.Setup.outputs.version }}
