---
name: testing

on:
  workflow_dispatch:

env:
  image: testdevops
  account: ${{ secrets.GCP_DEV_ACC }}
  creds: ${{ secrets.GCP_DEV }}

jobs:
  Setup:
    uses: ./.github/workflows/getLastVersion.yml
    with:
      image: $image
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_DEV_ACC }} 
      

  testit:
    runs-on:  ubuntu-latest
    
    steps:
      - uses: ./.github/workflows/getLastVersion.yml
        id: version
        with:
          image: testdevops
          account:  ${{ env.account }}
          GCPCreds: ${{ env.creds }}
      - run: echo ${{ steps.Setup.outputs.version }}
