---
name: testing

on:
  workflow_dispatch:

jobs:
  Setup:
    uses: ./.github/workflows/getVersion.yml
    with:
      image: testdevops
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_DEV }} 

  testit:
    runs-on:  ubuntu-latest
    needs: Setup

    steps:
      - run: echo ${{ needs.Setup.outputs.current_version }}
      - run: echo ${{ needs.Setup.outputs.new_version }}
