---
name: testing2

on:
  workflow_dispatch:

jobs:
  seeit:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout helm-repo
        uses: actions/checkout@v3

      - run: echo ${{ hashFiles('**/pom.xml') }} 