---
name: GCPSetup
description: 'Setup GCP environment'

inputs:
  GCPaccount:
    required: true
    description: GCP acount
  GCPCreds:
    required: true
    description: GCP credentials

runs:
  using: "composite"
  steps:
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.GCPCreds }}'

    - name: K8s login
      shell: bash
      run: |
        gcloud components install gke-gcloud-auth-plugin
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials primary-cluster --zone us-east1-b --project ${{ inputs.GCPaccount }}
