---
name: GCPSetup
description: 'Setup GCP environment'

inputs:
  GCPaccount:
    required: true
    description: GCP acount
  GCPCreds:
    required: true
    description: GCP credentials
  k8sSetup:
    required: false
    default: ""
    description: "install or not k8s credentials, with TRUE Sas string"

runs:
  using: "composite"
  steps:
    - uses: 'google-github-actions/setup-gcloud@v0'

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.GCPCreds }}'

    - shell: bash
      run: |
        if [ "${{ inputs.k8sSetup }}" = "TRUE" ]; then
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials primary-cluster --zone us-east1-b --project ${{ inputs.GCPaccount }}
        else
          echo "Skiping k8s setup"
        fi
